{% set name = "pyvpt2" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyvpt2-{{ version }}.tar.gz
  sha256: ef81415f98996ea5d0de45924aa27f05e9201d69090da177e5e0a9346d890873

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - setuptools-git-versioning
    - pip
  run:
    - python >={{ python_min }}
    - pydantic
    - numpy
    - qcelemental
    - qcengine
    - psi4 >=1.8

test:
  imports:
    - pyvpt2
  commands:
    - pip check
    - python -c "import pyvpt2;assert pyvpt2.__version__ == '{{ version }}', f'{pyvpt2.__version__=} differs from recipe=\'{{ version }}\''"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/philipmnel/pyvpt2
  summary: Package to calculate VPT2 anharmonic frequencies.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://philipmnel.github.io/pypvt2/
  dev_url: https://github.com/philipmnel/pyvpt2

extra:
  recipe-maintainers:
    - philipmnel
